### ISSUE TITLE
Проверить валидность написаных ранее json схем и скриптов добавления данных

### ISSUE THREAD

**Issue by InRedikaWB** [itmo-mpa/mpa-db-and-data#3]

**Comment by InRedikaWB** [comment]
Также нужно залить всю нужную информацию по лекарствам в репо и гайд по накатыванию, если нужно.

**Comment by darksidersstrife** [comment]
Текущий скрипт скоро станет невалидным, так как в базе предикаты выделили в отдельную таблицу
